### PR TITLE
refactor dotenv parser in order to support multi-line variable values declaration

### PR DESCRIPTION
**Pull request by ndeloof**
This is a clone PR for https://github.com/joho/godotenv/pull/118

### CODE REVIEW

**Comment by ndeloof** [comment]
@x1unix sorry to bother you with this, we'd like to adopt your PR for compose support of dotEnv file, but our oss contribution policy require all commits to be signed-off (git -s).
Would you mind amending your `value-separator` branch for this? 🙏

**Comment by x1unix** [comment]
@ndeloof done

**Comment by x1unix** [comment]
@ndeloof can I contribute any additional fixes directly to this repo? A few projects on my job also depend on my hotfix and there is no ETA when PR will be merged into upstream.

**Comment by ndeloof** [comment]
@x1unix sure, you can contribute additional fixes, as long as you feel those are relevant in the context of .env support in docker compose (or related) projects.
Please notice we have only kept the "parser" in this repo, as this is not expected to be used as a command line.

**Pull request merged**
